[workspace]
members = ["benchmarks", "cli"]
default-members = [".", "cli"]
resolver = "3"

[package]
name = "yurine"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3"
thiserror = "2.0.20"
zerocopy = "0.8"

[dev-dependencies]
approx = "0.5.1"
