[workspace]
members = ["benchmarks", "cli"]
default-members = [".", "cli"]
resolver = "3"

[package]
name = "yurine"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.11"
thiserror = "2.0.20"
zerocopy = { version = "0.8.54", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
